django_catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include
from django.urls import path

from main.sitemaps import CategorySitemap
from main.sitemaps import CollectionSitemap
from main.sitemaps import ProductSitemap
from main.views import robots_txt

handler404 = "main.views.tr_handler404"
handler505 = "main.views.tr_handler505"

sitemaps = {
    "category": CategorySitemap,
    "collection": CollectionSitemap,
    "product": ProductSitemap,
}

admin.site.site_header = "Мебель тут"


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", robots_txt),
    path("", include("main.urls")),
]

if settings.DEBUG:

    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path("", home, name="home"),
    path("catalog/", catalog, name="catalog"),
    path("product/<str:slug>/", currentProduct, name="current-product"),
    path("catalog/<str:slug>/", currentCategory, name="current-category"),
    path("catalog/<str:slug>/collections/", collections, name="current-collections"),
    path(
        "catalog/<str:slug>/collections/<str:slug2>/",
        currentCollectionFromCategory,
        name="collections-category",
    ),
    path("collections/<str:slug>/", currentCollection, name="current-collection"),
    path("sales/", sales, name="sales"),
    path("contacts/", contacts, name="contacts"),
    path("search/", searchHendler, name="search"),
    path("manufacturer/<str:slug>/", currentManufacturer, name="current-manufacturer"),
    path(
        "collection-autocomplete/",
        CollectionAutocomplete.as_view(),
        name="collection-autocomplete",
    ),
]

main/models.py
import random

from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.html import mark_safe
from pytils.translit import slugify

from .utils import unique_slugify


def get_rating():
    return random.randrange(1, 1000)


def get_filename(filename):
    filename_mas = filename.split(".")
    file_ext = filename_mas[-1]
    filename_mas.pop()
    file_base = ".".join(filename_mas)
    file_base = slugify(file_base)
    return file_base + "." + file_ext


def product_directory_path(instance, filename):
    filename = get_filename(filename)
    return "category_{0}/product_{1}/{2}".format(
        instance.category.slug, instance.slug, filename
    )


def image_directory_path(instance, filename):
    filename = get_filename(filename)
    return "category_{0}/product_{1}/{2}".format(
        instance.product.category.slug, instance.product.slug, filename
    )


def collection_directory_path(instance, filename):
    filename = get_filename(filename)
    return "collection_{0}/{1}".format(instance.slug, filename)


class Category(models.Model):
    name = models.CharField("Категория", max_length=100, blank=False, null=False)
    slug = models.SlugField("Ссылка", default="", unique=True)
    number = models.IntegerField("Номер в списке", blank=True, unique=True)
    isCabinet = models.BooleanField("Корпусная мебель?", default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def get_absolute_url(self):
        if self.isCabinet:
            return reverse("current-collections", kwargs={"slug": self.slug})
        else:
            return reverse("current-category", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name)

        if not self.number:
            self.number = Category.objects.count() + 1

        super().save(*args, **kwargs)


class Manufacturer(models.Model):
    name = models.CharField("Производитель", max_length=100, blank=False, null=False)
    slug = models.SlugField("Ссылка", null=False, blank=False, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Производитель"
        verbose_name_plural = "Производители"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("current-manufacturer", kwargs={"slug": self.slug})


class Collection(models.Model):
    name = models.CharField("Коллекция", max_length=100, blank=False, null=False)
    manufacturer = models.ForeignKey(
        Manufacturer, verbose_name="Производитель", null=True, on_delete=models.SET_NULL
    )
    category = models.ManyToManyField(
        Category, verbose_name="Категория", related_name="CategoryInCollection"
    )
    image = models.ImageField("Фото категории", upload_to=collection_directory_path)
    slug = models.SlugField("Ссылка", default="", null=False, blank=False, unique=True)

    def __str__(self):
        return self.name

    @property
    def image_preview(self):
        if self.image:
            return mark_safe(
                '<img src="{}" width="auto" height="250" />'.format(self.image.url)
            )
        return ""

    class Meta:
        verbose_name = "Коллекция"
        verbose_name_plural = "Коллекции"

    def get_absolute_url(self):
        return reverse("current-collection", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)


class Product(models.Model):
    name = models.CharField("Название", max_length=100, blank=False, null=False)
    manufacturer = models.ForeignKey(
        Manufacturer, verbose_name="Производитель", null=True, on_delete=models.SET_NULL
    )
    category = models.ForeignKey(
        Category,
        verbose_name="Категория",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="category",
    )
    collection = models.ForeignKey(
        Collection,
        verbose_name="Коллекция",
        null=True,
        on_delete=models.SET_NULL,
        blank=True,
    )
    collectionCategory = models.ManyToManyField(
        Category,
        blank=True,
        verbose_name="Категория для коллекции",
        related_name="category2collection",
    )
    isOnSale = models.BooleanField("Акция")
    rating = models.IntegerField(
        "Рейтинг",
        blank=False,
        null=False,
        validators=[MaxValueValidator(1000), MinValueValidator(1)],
        default=get_rating,
    )
    mainImage = models.ImageField("Главное фото", upload_to=product_directory_path)
    slug = models.SlugField("Ссылка", default="", null=False, blank=False, unique=True)
    date = models.DateTimeField("Дата добавления", default=timezone.now)
    price = models.DecimalField(
        "Цена", decimal_places=2, max_digits=7, default=0, blank=False, null=False
    )

    @property
    def mainImage_preview(self):
        if self.mainImage:
            return mark_safe(
                '<img src="{}" width="auto" height="250" />'.format(self.mainImage.url)
            )
        return ""

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def get_absolute_url(self):
        return reverse("current-product", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)

        """
        Compression
        """

    #     if self.__mainImage != self.mainImage and self.mainImage:
    #         image_compress(self.mainImage.path, width=800, height=800)

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.__mainImage = self.mainImage if self.pk else None


class ProductImage(models.Model):
    image = models.ImageField("Фото", upload_to=image_directory_path)
    product = models.ForeignKey(
        Product, verbose_name="Товар", null=True, on_delete=models.SET_NULL
    )

    def __str__(self):
        return f"Фото {self.product.name}"

    @property
    def image_preview(self):
        if self.image:
            return mark_safe(
                '<img src="{}" width="auto" height="250" />'.format(self.image.url)
            )
        return ""

    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фото"


class Specs(models.Model):
    product = models.ForeignKey(
        Product, verbose_name="Товар", null=True, on_delete=models.SET_NULL
    )

    SPECS_CHOICES = (
        ("Length", "Длина"),
        ("Width", "Ширина"),
        ("Height", "Высота"),
        ("Depth", "Глубина"),
        ("Weight", "Вес"),
        ("Bed length", "Длина спального места"),
        ("Bed width", "Ширина спального места"),
        ("Transformation mechanism", "Механизм трансформации"),
        ("The presence of drawers for linen", "Наличие ящиков для белья"),
        ("Corner", "Угол"),
        ("Material", "Материал"),
        ("Color", "Цвет"),
        ("Maximum load", "Максимальная нагрузка"),
        ("Tabletop thickness", "Толщина столешницы"),
        ("Additional Information", "Дополнительная информация"),
        ("Link", "Ссылка"),
    )

    UNIT_CHOICES = (
        ("mm", "мм"),
        ("sm", "см"),
        ("pc", "шт"),
        ("kg", "кг"),
    )

    param = models.CharField(
        "Параметр", max_length=100, choices=SPECS_CHOICES, blank=False, null=False
    )
    value = models.CharField("Значение", max_length=255, blank=False, null=False)
    unit = models.CharField(
        "Ед. измерения", max_length=10, choices=UNIT_CHOICES, blank=True, null=True
    )

    def __str__(self):
        return f"{self.product.name}"

    class Meta:
        verbose_name = "Характеристика"
        verbose_name_plural = "Характеристики"


class Address(models.Model):
    name = models.CharField(
        "Название", max_length=50, blank=False, null=False, default="Мебель тут"
    )
    street = models.CharField("Улица", max_length=20, blank=False, null=False)
    number = models.IntegerField("Дом", blank=False, null=False)
    building = models.CharField("Корпус", max_length=5, blank=False, null=False)

    class Meta:
        verbose_name = "Адрес"
        verbose_name_plural = "Адреса"

    def __str__(self):
        return f"{self.name}"


class Phone(models.Model):
    phone = models.CharField("Номер", max_length=20, blank=False, null=False)
    isViber = models.BooleanField("Viber")
    store = models.ForeignKey(
        Address, verbose_name="Магазин", null=True, on_delete=models.SET_NULL
    )

    class Meta:
        verbose_name = "Телефон"
        verbose_name_plural = "Телефоны"

    def __str__(self):
        return self.phone


class Feedback(models.Model):
    name = models.CharField("Имя", max_length=20, blank=False)
    phone = models.CharField("Номер", max_length=20, blank=False)
    product = models.ForeignKey(
        Product, verbose_name="Товар", on_delete=models.DO_NOTHING
    )
    product_name = models.CharField(
        "Название товара", max_length=30, blank=False, default="Товар"
    )
    date = models.DateTimeField("Дата добавления", default=timezone.now)
    link = models.URLField(default="http://127.0.0.1:8000/")

    def __str__(self):
        return f"{self.name} {self.phone}"

    class Meta:
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"

main/forms.py
from dal import autocomplete
from django import forms

from .models import Feedback
from .models import Product


class AddFeedbackForm(forms.ModelForm):
    name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"required": "required", "rows": 1, "placeholder": "Алексей"}
        ),
    )
    phone = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "required": "required",
                "class": "art-stranger",
                "rows": 1,
                "placeholder": "+375 (__) ___-__-__",
            }
        ),
    )

    class Meta:
        model = Feedback
        fields = ["name", "phone"]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        widgets = {
            "collection": autocomplete.ModelSelect2(
                url="collection-autocomplete",
                forward=["manufacturer"],
                attrs={
                    "data-theme": "admin-autocomplete",
                    "class": "unfold-admin-autocomplete",
                },
            ),
        }

main/templates/main/collections.html
{% extends 'main/base.html'%}
{% load static %}

{% block head %}
<meta name="keywords" content="Каталог, Коллекции, Барановичи, Мебель, Купить">
{% endblock %}

{% block title %}
{{title}} | Мебель тут Барановичи
{% endblock %}

{% block body %}
{% include "main/nav.html" %} 
{% endblock %}

{% block content %}
<div class="content2">
    <div class="items_list" id="main">
        <span onclick="navHandler()"><img src="{% static 'main/img/chevron-right.svg' %}" alt="меню" id="menu_btn"></span>
        <div class="collection">
        {% if page_obj %}
                {% for x in page_obj %}
                    <div class="catalog_image_container">
                        <a href="{% url 'collections-category' slug=findCategory.slug slug2=x.slug %}">
                            <h1>{{x.name}}</h1><h3>{{x.manufacturer}}</h3></a>
                        <div class="collection_photo">
                            <a href="{% url 'collections-category' slug=findCategory.slug slug2=x.slug %}"><img src="{{ x.image.url }}" alt=""></a>
                        </div>
                    </div>
                {% endfor %}
                {% else %}
                <div id="empty">
                    <h1>Нет коллекций</h1>
                </div>
        {% endif %}
        </div>
        {% include "main/pagination.html" %} 
    </div>
</div>

{% endblock %}


{% block script %}
<script src="https://kit.fontawesome.com/406fbec51e.js" crossorigin="anonymous"></script>
{% endblock %}

main/templates/main/contacts.html
{% extends 'main/base.html'%}
{% load static %}


{% block head %}
<meta name="keywords" content="Каталог, Барановичи, Мебель, Купить, Телефоны, Адреса">
<!-- Facebook Meta Tags -->
<meta property="og:url" content="https://mebeltut24.by/">
<meta property="og:type" content="website">
<meta property="og:title" content="Мебель тут">
<meta property="og:description" content="Магазины мебели в Барановичах. Телефоны:  {% for x in phones%} {{x.phone}} {% endfor %}  inst: @mebeltutbaranovichi">
<meta property="og:image" content="https://mebeltut24.by/static/main/img/logo.png">

<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="mebeltut24.by">
<meta property="twitter:url" content="https://mebeltut24.by/">
<meta name="twitter:title" content="Мебель тут">
<meta name="twitter:description" content="Магазины мебели в Барановичах. Телефоны:  {% for x in phones%} {{x.phone}} {% endfor %}  inst: @mebeltutbaranovichi">
<meta name="twitter:image" content="https://mebeltut24.by/static/main/img/logo.png">

<!-- Meta Tags Generated via https://www.opengraph.xyz -->
<script src="https://api-maps.yandex.ru/2.1/?apikey=f44be221-5cc9-4fd4-92f8-588eb59eb448&lang=ru_RU" type="text/javascript">
</script>
{% endblock %}
{% block title %}
Контакты | Мебель тут
{% endblock %}

{% block content %}
<div class="content">
    <div class="contacts_body">
        <div>
            <h1>Контакты</h1>
            <p>г. Барановичи</p>
            <ul class="small">
                {% for x in address%}
                    <h2>{{x.name}}</h2>
                    <p>ул. {{ x.street }} {{x.number}}{{x.building}}</p>
                    <p>{% for i in phones %}
                            {% if i.store == x %}
                                <a class="header_item tel" id="footer_tel" href="tel:{{i.phone}}">{{i.phone}}</a>
                                {% if i.isViber %}<img src="{% static 'main/img/viber.svg'%}" alt="">{% endif %}
                            {% endif %}
                        {% endfor %}
                    </p>
                {% endfor %}
            </ul>
            <div id="time_container">
                <h2>Время работы</h2>
                <h3 class="time">Пн-Пт: 10:00 - 19:00</h3>
                <h3 class="time">Cб-Вс: 10:00 - 16:00</h3>
            </div>
            <div id="flex_div">
                <div class="zero">
                    <h2>Email:</h2>
                    <p>uma-mebel@list.ru</p>
                </div>
                <div class="zero">
                    <h2>Instagram:</h2>
                    <p><a class="header_item" id="footer_inst" href="https://www.instagram.com/mebeltutbaranovichi/">@mebeltutbaranovichi</a></p>
                </div>
            </div>
        </div>
        <div id="map_container">
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
<script type="text/javascript">
    ymaps.ready(init);
    function init() {
        var myMap = new ymaps.Map("map_container", {
            // Координаты центра карты
            center: [53.132552, 25.993283],
            // Масштаб карты
            zoom: 13,
            // Выключаем все управление картой
            controls: ['zoomControl']
        });

        var myGeoObjects = [];

        // Указываем координаты метки
        
        
        first = new ymaps.Placemark([53.152019, 26.026961], {
            balloonContentBody: 'Мебель тут<br>ул. Пролетарская 48А<br><a href="tel:+375-33-322-61-15">+375-33-322-61-15</a><br><a target="_blank" href="https://yandex.by/maps/org/mebel_tut/1064530150/?ll=26.026961%2C53.152019&z=17">Перейти в карты</a>',
        }, {
            iconLayout: 'default#image',
            // Путь до нашей картинки
            iconImageHref: 'https://mebeltut24.by/static/main/img/logo.png',
            // Размеры иконки
            iconImageSize: [40, 40],
            // Смещение верхнего угла относительно основания иконки
            iconImageOffset: [-20, -30]
        });
        
        second = new ymaps.Placemark([53.113425, 25.967842], {
            balloonContentBody: 'Мебель тут ПЛЮС<br>ул. Брестская 270Д<br><a href="tel:+375-33-376-06-77">+375-33-376-06-77</a><br><a target="_blank" href="https://yandex.by/maps/org/mebel_tut/235141099136/?ll=25.967591%2C53.113249&z=17">Перейти в карты</a>',
        }, {
            iconLayout: 'default#image',
            // Путь до нашей картинки
            iconImageHref: 'https://mebeltut24.by/static/main/img/logo.png',
            // Размеры иконки
            iconImageSize: [40, 40],
            // Смещение верхнего угла относительно основания иконки
            iconImageOffset: [-20, -30]
        });
    
        myGeoObjects = [first, second]
        
        var clusterer = new ymaps.Clusterer({
            clusterDisableClickZoom: false,
            clusterOpenBalloonOnClick: false,
        });
        

        clusterer.add(myGeoObjects);
        myMap.geoObjects.add(clusterer);
    
        
        if (window.matchMedia("(max-width: 850px)").matches) {
        	myMap.setZoom(12);
        };
    }
</script>
{% endblock %}

main/templates/main/nav.html
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <div class="vertmenu">
        <h1>Каталог:</h1>
        <hr>
        <ul id="menu_left">
            {% for x in categories %}
                <li>
                    <a {% if x == findCategory %}class="active"{% endif%}href="{{ x.get_absolute_url }}">{{ x.name }}</a>
                <li>
            {% endfor %}
        </ul>
    </div>
</div>

main/templates/main/product.html
{% extends 'main/base.html'%}
{% load static %}
{% load thumbnail %}

{% block head %}
<link rel="stylesheet" href="{% static 'main/css/product.css'%}">
<link rel="stylesheet" href="{% static 'main/css/customAlert.css'%}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bigger-picture@1.1.7/dist/bigger-picture.min.css">
<meta name="keywords" content="{{current.name}}, {{current.manufacturer}}, {{current.category}}, {% if current.collection %}{{current.collection}},{% endif %} Барановичи, Мебель, Купить">
<!-- Facebook Meta Tags -->
<meta property="og:url" content="https://mebeltut24.by/">
<meta property="og:type" content="website">
<meta property="og:title" content="Мебель тут">
<meta property="og:description" content="{{current.name}}, {{current.manufacturer}}, {% if current.collection %}{{current.collection}},{% endif %} Магазины мебели в Барановичах. Телефоны:  {% for x in phones%} {{x.phone}} {% endfor %}  inst: @mebeltutbaranovichi">
<meta property="og:image" content="{{current.mainImage.url}}">

<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="mebeltut24.by">
<meta property="twitter:url" content="https://mebeltut24.by/">
<meta name="twitter:title" content="Мебель тут">
<meta name="twitter:description" content="{{current.name}}, {{current.manufacturer}}, {% if current.collection %}{{current.collection}},{% endif %} Магазины мебели в Барановичах. Телефоны:  {% for x in phones%} {{x.phone}} {% endfor %}  inst: @mebeltutbaranovichi">
<meta name="twitter:image" content="{{current.mainImage.url}}">

<!-- Meta Tags Generated via https://www.opengraph.xyz -->
{% endblock %}

{% block title %}
{{title}} | Мебель тут Барановичи
{% endblock %}

{% block body %}
{% include "main/nav.html" %}
{% endblock %}

{% block content %}
<div class="content2">
    <div class="items_list" id="main">
        <span onclick="navHandler()"><img src="{% static 'main/img/chevron-right.svg' %}" alt="меню"
                id="menu_btn"></span>
        <div class="product">
            <div class="swiper-container">
                <div class="swiper mySwiper2">
                    <div class="swiper-wrapper" id="images">
                            <div class="swiper-slide">
                                <a
                                    href="{{ current.mainImage.url }}"
                                    data-img="{{ current.mainImage.url }}"
                                    data-thumb="{% thumbnail current.mainImage 600x600 %}"
                                    data-alt="Главное фото {{ current.name }}"
                                    data-height="2000"
                                    data-width="3000"
                                >
                                    <img
                                    src="{% thumbnail current.mainImage 600x600 %}"
                                        alt="Главное фото {{ current.name }}"
                                    />
                                </a>
                            </div>
                        {% for x in currentImages %}
                            <div class="swiper-slide">
                                <a
                                    href="{{ x.image.url }}"
                                    data-img="{{ x.image.url }}"
                                    data-thumb="{% thumbnail x.image 600x600 %}"
                                    data-alt="Фото {{ current.name }}"
                                    data-height="2000"
                                    data-width="3000"
                                >
                                    <img
                                    src="{% thumbnail x.image 600x600 %}"
                                        alt="Фото {{ current.name }}"
                                    />
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="swiper-button-next"></div>
                    <div class="swiper-button-prev"></div>
                </div>
                <div thumbsSlider="" class="swiper mySwiper">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide"><img src="{{ current.mainImage.url }}" alt=""></div>
                        {% for x in currentImages %}
                            <div class="swiper-slide"><img src="{{ x.image.url }}" alt=""></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="info_container">
                <h1>{{current.name}}
                    {% if current.rating >= 900 %}
                        <div class="bestseller_product">Хит продаж</div>
                    {% elif current.isOnSale %}
                        <div class="sale_product">Акция</div>
                    {% elif new %}
                        <div class="new_product">Новинка</div>
                    {% endif %}
                </h1>
                {% if current.price != 0 %}
                    <h3 id="price">Цена: {{current.price}} <span>руб</span></h3>
                {% else %}
                    <h3 id="price">Под заказ</h3>
                {% endif %}
                <p id="manufacturer">Производитель: <a
                        href="{{current.manufacturer.get_absolute_url}}">{{current.manufacturer}}</a></p>
                {% if current.collection %}
                <p id="collection">Коллекция: <a
                        href="{{current.collection.get_absolute_url}}">{{current.collection}}</a></p>
                {% endif %}
                <hr>
                <div class="info">
                    <h2>Характеристики:</h2>
                    {% for x in currentSpecs %}
                        {% if x.param == 'Link' %}
                             <p><span>{{ x.get_param_display }} {%if x.unit %}, {{x.get_unit_display}} {% endif %}</span><span><a href="{{x.value }}">Каталог</a></span></p>
                        {% else %}
                            <p><span>{{ x.get_param_display }} {%if x.unit %}, {{x.get_unit_display}} {% endif %}</span><span>{{x.value }}</span></p>
                        {% endif %}
                    {% endfor %}
                </div>
                <hr>
            </div>
            <div class="feedback">
                <h2>Заинтересовало?</h2>
                <p>Оставьте свои данные, наш специалист перезвонит вам</p>
                <form action="{{ current.get_absolute_url}}" method="post" novalidate enctype="multipart/form-data"
                    id="feedback_form">
                    {% csrf_token %}
                    <div><label for="name">Имя:</label>
                        {{ feedback.name }}
                        <hr>
                    </div>
                    <div><label for="tel">Номер телефона:</label>
                        {{ feedback.phone }}
                        <hr>
                    </div>
                    <button type="submit">Перезвонить мне</button>
                </form>
            </div>
            <div class="warning">
                <p>*Цветопередача на фотографиях может не соответствовать оригиналу</p>
                <p>**Сайт не является интернет магазином. Цена представлена в ознокомительных целях.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
<script src="https://kit.fontawesome.com/406fbec51e.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"
    integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="{% static 'main/js/maska-nomera.js' %}" type="text/javascript"></script>
<script src="{% static 'main/js/customAlert.js' %}" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/bigger-picture@1.1.7/dist/bigger-picture.min.js"></script>
<script>
    let swiper = new Swiper(".mySwiper", {
        spaceBetween: 10,
        slidesPerView: 4,
        freeMode: true,
        watchSlidesProgress: true,
        loop: true,
    });


    let swiper2 = new Swiper(".mySwiper2", {
        spaceBetween: 10,
        loop: true,
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
        thumbs: {
            swiper: swiper,
        },
    });


    $('.art-stranger').mask('+375 (99) 999-99-99');
    $.fn.setCursorPosition = function (pos) {
        if ($(this).get(0).setSelectionRange) {
            $(this).get(0).setSelectionRange(pos, pos);
        } else if ($(this).get(0).createTextRange) {
            var range = $(this).get(0).createTextRange();
            range.collapse(true);
            range.moveEnd('character', pos);
            range.moveStart('character', pos);
            range.select();
        }
    };

    $('input[type="tel"]').click(function () {
        $(this).setCursorPosition(6);  // set position number
    });    

    if('{{ isFeedback }}' == 'true'){
        customAlert.alert("{{feedback_message}}","{{feedback_title}}")
        //window.location.replace('/product/{{ current.slug }}');
    }

    let bp = BiggerPicture({
	    target: document.body,
    })

    // grab image links
    let imageLinks = document.querySelectorAll('#images .swiper-slide > a')

    // add click listener to open BiggerPicture
    for (let link of imageLinks) {
        link.addEventListener("click", openGallery);
    }

    // function to open BiggerPicture
    function openGallery(e) {
	    e.preventDefault()
	    bp.open({
		    items: imageLinks,
		    el: e.currentTarget,
            intro: 'fadeup'
	    })
    }
</script>
{% endblock %}